jobs:
  - name: pipelines-demo-manifest-mini
    type: manifest
    steps:
     - IN: pipelines-demo-image-mini
     - TASK: managed
    on_success:
     - NOTIFY: irc-mini

  - name: deploy-pipelines-demo-mini
    type: deploy
    flags:
      - job-flag-mini
    steps:
      - IN: pipelines-demo-manifest-mini
      - IN: ecs-cluster-mini
      - IN: docker-options-mini
      - IN: replicas-mini
      - TASK: managed
        deployMethod: upgrade

  - name: runSh-mini
    type: runSh
    runtime:
      nodePool: c7-test
    allowPublicAccess: true
    steps:
      - IN: pipelines-demo-manifest-mini
      - TASK:
        - script: echo 'This block executes when the TASK starts'
        - script: echo "versionName=satble" >> $JOB_STATE/runSh.env;


  - name: runSh3-mini
    type: runSh
    steps:
      - IN: deploy-pipelines-demo-mini
      - TASK:
        - script: echo 'This block executes when the TASK starts'
        - script: echo "versionName=satble" >> $JOB_STATE/runSh3.env;


  - name: runSh-test
    type: runSh
    steps:
      - IN: replicas-mini
      - TASK:
        - script: echo 'This block executes when the TASK starts'
        - script: echo "versionName=satble" >> $JOB_STATE/runSh3.env;

  - name: mini-downstream
    type: manifest
    steps:
     - IN: runSh-mini
     - IN: mini-downstream-parent
     - TASK: managed

  - name: mini-downstream-child
    type: manifest
    steps:
     - IN: mini-downstream
     - TASK: managed
    flags:
      - downstream

  - name: mini-downstream-parent
    type: runSh
    allowPublicAccess: true
    steps:
      - OUT: mini-downstream
      - IN: mini-downstream-ancestor
      - TASK:
        - script: echo 'This block executes when the TASK starts'
        - script: echo "versionName=satble" >> $JOB_STATE/runSh.env;

  - name: mini-downstream-ancestor
    type: runSh
    allowPublicAccess: true
    steps:
      - TASK:
        - script: echo 'This block executes when the TASK starts'
        - script: echo "versionName=satble" >> $JOB_STATE/runSh.env;
